### PR TITLE
Add snapshots module

### PR DESCRIPTION
**Pull request by ikem-krueger**
The module is in a good shape and ready to merge. But before that, I'd like to get some feedback.

### CODE REVIEW

**Comment by mkreisl** [comment]
Hello, sorry I'm just getting back to you.

What I noticed right away when testing are the strange outputs, such as 
#,Snapshot [
 ]
and should actually be 
[ #,Snapshot ]
in my opinion.

As it is at the moment, I find it quite confusing, especially as the [ ] sometimes goes over 2 lines.

A correct output of this line can be found for example in 
Config -> System -> Network

There you don't have to select anything, you just have to press return to get to the lower menu.

What do you think?

**Comment by ikem-krueger** [comment]
I got what you mean. I see what I can do.

**Comment by mkreisl** [comment]
Hi, I see you have been busy, very nice. 
It looks much better already. only 2 things I noticed right away

1) for me the header and the menu are never on top of each other. on the one hand this is because of the german texts with umlauts, but also with `LC_ALL=en_US.utf8 xbian-config` they are not on top of each other.
Is this only the case with me?

With the following changes, the display is correct for me:
```
diff --git a/content/usr/local/include/xbian-config/modules/snapshots/dialogs b/content/usr/local/include/xbian-config/modules/snapshots/dialogs
index 6d2d82d..e897b02 100644
--- a/content/usr/local/include/xbian-config/modules/snapshots/dialogs
+++ b/content/usr/local/include/xbian-config/modules/snapshots/dialogs
@@ -195,7 +195,7 @@ function selectVolumeDlg() {
        "#;\ZbVolume"\
        "${MENU[@]}"
 
-       centerTxtFn "$HEADER" $(($DEFAULTWIDTH+6));
+       centerTxtFn "$HEADER" $(($DEFAULTWIDTH+7));
 
        showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+9));
 }
diff --git a/content/usr/local/include/xbian-config/modules/snapshots/main b/content/usr/local/include/xbian-config/modules/snapshots/main
index 722396f..1f02d32 100644
--- a/content/usr/local/include/xbian-config/modules/snapshots/main
+++ b/content/usr/local/include/xbian-config/modules/snapshots/main
@@ -47,7 +47,7 @@ function showGUIFn() {
        "#;\Zb"$(_ services.label.action)\
        "${MENU[@]}";
 
-       centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11));
+       centerTxtFn "$HEADER" $(($DEFAULTWIDTH+7));
        showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 11
 
        if [ $? -eq 0 ]; then
```

2) when starting an action I immediately waited for the query yes/no. but this didn't come but the function was executed immediately. Is a bit irritating at least with **rollback** or **delete**.

**Comment by mkreisl** [comment]
Oh, I forgot. Adjusted the Rows of the submenus:

```
diff --git a/content/usr/local/include/xbian-config/modules/snapshots/dialogs b/content/usr/local/include/xbian-config/modules/snapshots/dialogs
index 6d2d82d..e703ed1 100644
--- a/content/usr/local/include/xbian-config/modules/snapshots/dialogs
+++ b/content/usr/local/include/xbian-config/modules/snapshots/dialogs
@@ -195,9 +195,9 @@ function selectVolumeDlg() {
        "#;\ZbVolume"\
        "${MENU[@]}"
 
-       centerTxtFn "$HEADER" $(($DEFAULTWIDTH+6));
+       centerTxtFn "$HEADER" $(($DEFAULTWIDTH+7));
 
-       showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+9));
+       showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+8));
 }
 
 function selectSnapshotDlg() {
```

Looks better in my opinion

**Comment by ikem-krueger** [comment]
I had my problem applying your patches. I had to manually open the file and change the lines.

About your changes, they look fine for me. I integrate them.

> When starting an action I immediately waited for the query yes/no.

You mean a confirmation dialog? I will add that.

**Comment by mkreisl** [comment]
FYI: you shouldn't close the PR because I can't merge it like that.

**Pull request merged**
