### PR TITLE
Add snapshots module

### PR DESCRIPTION
**Pull request by ikem-krueger**
I wanted to use xbian-config to manage the btrfs snapshots. Hence I wrote a module for it.

The usage is fairly simple:

**GUI:**

"Snapshots - Manage snapshots" -> "Snapshot - Create snapshot of a volume" -> select volume
"Snapshots - Manage snapshots" -> "Rollback - Rollback to a snapshot of a volume" -> select volume -> select snapshot

**CMD:**

```bash
# list volumes
xbian-config snapshots listvol

# create snapshot for volume
xbian-config snapshots snapshot <volume>

# list snapshots for volume
xbian-config snapshots list <volume>

# rollback to snapshot
xbian-config snapshots rollback <volume> <snapshot>
```

I want you to review it, and if it fits, merge it.

Feedback is welcome.

### CODE REVIEW

**Comment by mkreisl** [comment]
Nice work :+1: 

Proposal for amendments:
1) change the name of the snapshots, as the formatting no longer fits with german umlauts due to UTF 16-bit character length. I have encountered this problem before.
Snapshot management -> Create, delete, rollback
2) function missing delete of snapshot

BTW, in case you haven't seen it, these management functions are already available in the XBian-Config GUI under Backup. But having them in the CLI can also be very useful.

**Comment by mkreisl** [comment]
> I saw them in the code, but not in the GUI.
> 
AFAIR it is an advanced function

> And I couldn't reach them, because every time I open this menu point, it instantly creates a backup, and that's something I didn't wanted. I wanted to manage the snapshots separatly from the backups.

I have already thought about that

**Comment by ikem-krueger** [comment]
The thing is, I only have a rough idea, how the menu system works.

As I understand it you can only have modules with the same name as the menu point.

So either way I have:

```
8:snapshots
8.1:create
8.2:delete
8.2:rollback
```
with the accourding modules:

```
modules/snapshots
modules/create
modules/delete
modules/rollback
```

Which is confusing, when you look into the modules folder.

Or I have:

```
8:snapshots
```
And have all in the module:

```
modules/snapshots
```

But lose the sub menu points.

**Comment by mkreisl** [comment]
I'm afraid i can't really help you there. i decided a long time ago to do only the absolutely necessary things in xbian-config CLI and everything else in the XBian-Config GUI. As far as xbian-config CLI is concerned, i've almost forgotten everything again.

My first thought was to move the snapshot thing to a submenu, but I have no idea where it would fit best.

**Comment by ikem-krueger** [comment]
I use Kodi with a different theme. And that the XBian-Config GUI isn't working for that theme. Hence I do the configuration mostly on the console.

**Comment by ikem-krueger** [comment]
Will close this pull request and work on it more.

**Comment by mkreisl** [comment]
Interesting. I was about to merge the PR

**Pull request closed without merging**
