### PR TITLE
Update functions

### PR DESCRIPTION
**Pull request by CurlyMoo**
Useless eval's

(Untested)

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Why is this not merged?

**Comment by mkreisl** [comment]
Read the commits: https://github.com/xbianonpi/xbian-package-config-shell/commit/50ec2e337af871c5d5f9a8d7ef3ad3c22cac64f2

**Comment by CurlyMoo** [comment]
I always merge user input first :smile:

**Comment by mkreisl** [comment]
Too much work to update your PR :smile:

**Pull request closed without merging**
